name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Step 1: Check out the repository
      uses: actions/checkout@v3

    - name: Step 2: Set up the Java Development Kit (JDK)
      uses: actions/setup-java@v3
      with:
        java-version: '17' # إصدار JDK أكثر استقرارًا
        distribution: 'temurin'

    - name: Step 3: Build the project with Maven
      run: mvn clean package

    - name: Step 4: Verify the generated JAR file
      run: dir target/*.jar
